---
- name: 'Create another user'
  hosts: localhost
  become: true
  tasks:
  - name: 'create new user named Ricardo'
    user: 
      name: 'Ricardo'
      state: present
  - name: "copy files to new user"
    file:
      path: /home/Ricardo
      state: directory
