---
- name: Play 1
  hosts: localhost
  tasks:
    - name: Execute command 'date'
      command: date

- name: Play 2
  hosts: localhost
  tasks:
    - name: install the latest version of Apache
      apt:
         name: httpd
         state: present
    - name: start web server
      service:
         name: httpd
         state: started
